name: Maestro UI Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  maestro-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install and Verify Maestro CLI
        run: |
          # Install Maestro CLI
          curl -Ls "https://get.maestro.mobile.dev" | bash
          
          # Add Maestro to PATH
          echo 'export PATH="$PATH:$HOME/.maestro/bin"' >> $GITHUB_ENV
          
          # Verify Maestro installation
          ~/.maestro/bin/maestro --version || echo "Maestro installation failed"

      - name: Install Maestro CLI Globally
        run: |
          # Move Maestro CLI to a globally accessible path
          sudo mv $HOME/.maestro/bin/maestro /usr/local/bin/
          
          # Verify Global Installation
          maestro --version || echo "Global Maestro installation failed"

      - name: Debug Maestro Installation
        run: |
          # Print PATH and check locations
          echo "PATH: $PATH"
          ls -la $HOME/.maestro/bin/
          which maestro

      - name: Run Maestro tests on Maestro Cloud
        run: ~/.maestro/bin/maestro cloud -e APP_ID=com.google.android.calculator --apiKey=${{ secrets.MAESTRO_CLOUD_API_KEY }} --app-file=app/Calculator.apk android
        env:
          MAESTRO_CLOUD_API_KEY: 164a4ca2-3f65-44ab-bf1c-2bde9a858fac
          MAESTRO_PROJECT_ID: ${APP_ID }